server:
  port: 8080 #配置访问端口
  servlet:
    context-path: / #配置访问时的项目名
spring:
  resource:
    static-locations: classpath:/static/,classpath:/templates/
  devtools:
    remote:
     restart:
      enabled: true #热加载
  datasource: #数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.11.113:3306/b2b?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
    #multipart:
     # enabled: true
      #max-file-size: 10MB
      #max-request-size: 100MB
  jackson:
     date-format: yyyy-MM-dd
     time-zone: GMT+8
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    #content-type: text/html
    cache: false
  mvc:
    view:
      suffix: .html
      prefix: /
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.aaa.ysemm.customer.entity
logging:
  level:
    com:
     example:
      demo:
       mapper: debug
